import Navbar from "@/components/navbar/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AboutLayout({children}: {children: React.ReactNode;}) {
  return (
    <>
    <Navbar/>
    <main className="flex flex-col items-center">
      <span className="text-lg">Hola mundo</span>
     {children}
    </main>
    </>
  );
}
